---
title: "Specific opportunities for improvements"
author: "Maja Martos"
subtitle: "Add a Subtitle if Needed"
output: pdf_document
csl: bmcemerg.csl
editor_options:
  markdown:
    wrap: 72
bibliography: bibliography.bib
---


```{r setup, include=FALSE }
setwd("~/trauma-opportunities-for-improvements")

source("main.R")

source("clean_all_predictors.R")
```



# Introduction


Trauma, clinically defined as physical injury and the body´s associated response, cause 4.4 million deaths every year worldwide [who2021, ref funkar inte]. However, mortality and morbidity related to trauma have been significantly reduced in modern countries since the introduction of trauma systems [alharbi2021]. Trauma systems have a long tradition within the military but were not implemented in civil health care until the 1960s-1970s when the report “Accidental Death and Disability: The Neglected Disease of Modern Society” was published in the US in 1966 [choi2021]. Since then, trauma systems have been put into practice in most modern countries with the aim to coordinate and improve management of critically injured patients, from onset of injury to high-level care in designated trauma centres [nswTraumaSystem]. 

The American College of Surgeons (ACS) committee on trauma provide guidelines for the ideal trauma system covering all components of the system: (I) trauma centres, (II) referral hospitals, (III) rehabilitation as well as a (IV) data collection and quality improvement. Quality improvement through continuous evaluation and identification of opportunities for improvement with subsequent corrective action plans constitute a cornerstone in the trauma system and should be systematically proceeded by all trauma centres (5,6). 

As injuries differ vastly by feature, risk and what constitute appropriate care, they should be separated when evaluated for comparability. For this purpose, the abbreviated injury scale (AIS) has been implemented as a standardised system to categories all types of injuries and their severity (7). The AIS is a 6 point scale scoring system that ranks the severity of injury for five anatomic regions (8). The ACS has further implemented the AIS system to divide trauma into different patient cohorts (9).


Opportunities for improvement (OFI), include all aspects of the trauma system and can be defined as deficiencies or aberrations from guidelines at any stage of care that could be avoided through optimised action (10) . When trauma leads to death, it can be sorted into either preventable or non-preventable. In both cases, OFIs can be detected regardless of whether the outcome could have been prevented. (11) Two widespread systems to study unanticipated deaths prevail; autopsy and multidisciplinary reviews through mortality and morbidity (M&M) conferences (12).

While autopsy provides information on cause and mechanism of death, it is costly and not always feasible due to ethical, legal and religious considerations (13). Neither does it provide information regarding the process of care. In this respect, M&M reviews present a more comprehensive assessment of the course of care (6). However, when discussing preventability of death, problems arise with respect to the sensitivity of putting the burden of blame on fellow colleagues and ambiguity regarding whether mortality is due to inappropriate care or not. To assess OFIs related to death, therefore constitute a more robust and feasible method to improve care of trauma patients (12).

To date a variety of studies based on OFIs have been conducted with the aim to identify recurrent errors for specific patient cohorts or trauma facilities. Socioeconomic, cultural and geographic issues, trauma characteristics and healthcare vary between countries and rural/city areas.  In 2020, a study in northern Alberta was conducted with challenging geography, limited health care resources and a high proportion of agricultural trauma in mind. Lack of equipment and personnel were identified as key areas of improvement (14). Other cohorts focusing on e.g., haemorrhage, which is the leading cause of trauma related death, have identified specific OFIs for this patient group (15).

Nordic countries differ from other countries with colder climate, fewer cases of serious trauma annually and long distances to trauma centres as few hospitals are equipped to treat trauma-1 patients (16) (17). Although increasing over the past few years, a systematic review covering trauma-related studies in Nordic countries the years 1995–2018, show that they fall behind when it comes to number of publications on the subject compared with other economically similar countries (16).

In Sweden surgical care is highly centralised and no uniform national organization for trauma care is at place. This makes evaluation of competence and performance at site crucial to maintain high quality and avoid unnecessary risks for the patient (18). Previous studies of Swedish trauma data have analysed OFIs as clustered variable for overlapping cohorts. In this study four non-overlapping cohorts were studied and specific categories of OFIs were found for each cohort. 


the patients mean age was `r mean.age`

# Methods


**Study design** 

A registry-based cohort study linking data from the Swedish trauma registry SweTrau and trauma care quality database at the KUH. The combined data were further assessed through multinominal logistic regression to identify specific opportunities for improvements (OFI), identified by the multidisciplinary review board at the KUH All data were managed and analysed in R software.

**Aim**

Hitherto, studies of the trauma registry held by the KUH have used the OFI as a composite measure for all potential lapses leading to un-optimal care. Although this approach offers insight to whether opportunities for improvement exist, it is insufficient in providing health care workers with guidance to actions that may improve care of trauma patients. Hence, in this study, all specific parameters included in OFI were analysed individually to analyse their explanatory value of OFI for four categories of trauma, with the aim to identify the main areas of improvement. 



**Setting**
From 2010, The Swedish Trauma society holds a national registry over patients suffering serious trauma in Sweden. Patients included in the registry have either suffered traumatic events leading to either a trauma alarm or a new injury severity score (NISS) over 15. In 2021, a total of 10,528 patients were registered (an increase of 17% from 2020). Of these, 90% were assigned to blunt traumas such as falls, traffic accidents and blunt force traumas with objects and the rest to penetrating trauma such as gun shots and stabbing. (SweTrau2021)

In Sweden the Karolinska University hospital covers the regions of Stockholm, Gotland, Södermanland and Västmanland, equivalent to 3 million residents. This is just on pair with the minimum number of patients needed to be recognized as a quality trauma centre internationally. The hospital is also the only facility in Sweden to qualify as a trauma-1 hospital by American standards (19). 

To detect non-optimal treatment, treating hospitals evaluate trauma patients at a M&M conference held by a multidisciplinary board appointed by the hospital. The board consists of a surgeon, an anaesthetist, a trauma nurse and in presence of specific injuries (e.g., intracranial, orthopaedical or thoracic/vascular), specialists from appropriate specialties. Competences involved in the direct care of the patient are free to attend the conference but should not take part in the review. (Dödsfallsanalys2021)

Patients are selected to M&M-conference based on the audit filters listed below and are thereby selected for review algorithmically and independent of mortality to study OFIs. If one or more of the audit filters apply, the patient is manually assessed by a nurse who goes through the patient journal and makes a final judgement of whether the patient should be brought to conference. At conference, the multidisciplinary board determines the cause of death and reviews the case for suboptimal handling and treatment to identify opportunities for improvement (20).

Audit filters: 
+- Systolic blood pressure less than 90
+- Glasgow coma scale less than 9 and not intubated
+- Injury severity score greater than 15 but not admitted to the intensive care unit
+- Time to acute intervention more than 60 minutes from arrival to hospital
+- Time to computed tomography more than 30 minutes from arrival to hospital
+- No anticoagulant therapy within 72 hours after traumatic brain injury
+- The presence of cardio-pulmonary resuscitation with thoracotomy
+- The presence of a liver or spleen injury
+- Massive transfusion, defined as 10 or more units of packed red blood cells within 24 hours.

At the Karolinska University Hospital, results from the conferences are stored in a local trauma care quality database where all areas of improvement are registered and collectively stored in a variable, OFI. 

**Study population** 

We will study data of patients registered in both the Swedish trauma registry from SweTrau and the trauma quality data base at the KUH meeting the following criteria:

+- Older than 15 year
+- A NISS > over 15 or a ISS >9 
+- Being reviewed at an M&M conference 
+- Belonging to one of the following cohorts:
+  1. Blunt multisystem trauma with traumatic brain injury
+  2. Blunt multisystem trauma without traumatic brain injury
+  3. Penetrating trauma
+  4. Isolated severe traumatic brain injury


**Variables** 

The primary outcome was opportunities for improvements (OFI) detected by the M&M teams at the Karolinska University hospital. The variable is categorical with the OFIs listed below as possible outcomes.  The exposure were different patient cohorts grouped by mechanism of injury, (1) blunt multisystem trauma with traumatic brain injury, (2) blunt multisystem trauma without traumatic brain injury, (3) penetrating trauma, (4) isolated severe traumatic brain injury. Each cohort studied was distinguished according to definitions provided by the ACS. 

+ 1.	Blunt multisystem trauma: Blunt trauma with injuries of Abbreviated Injury Score (AIS) ≥ 3 in at least two of the following AIS body regions: head, face, neck, thorax, abdomen, spine, or upper and lower extremities.
+ 2.	Blunt multisystem trauma without traumatic brain injury: Blunt trauma with injuries of AIS ≥ 3 limited to only one AIS body region, with all other body regions having a maximum AIS ≤ 
+ 3.	Penetrating trauma: At least one AIS ≥ 3 injury in any of the following AIS body regions: neck, thorax, and abdomen.
+ 4.	Isolated severe traumatic brain injury: Best GCS within the first 24 h ≤ 8 OR Best motor score ≤ 3 within the first 24 h, and one of:
+  a.	Abnormal CT brain (hematoma, contusion, swelling, herniation, compression of basal cisterns
+  b.	Normal CT brain AND (Age > 40 y OR SBP <90 mmHg on ED arrival) OR posturing (GCS motor = 2, 3)

OFIs Identified at M&M conference:
+- Missed injury
+- Problem with communication
+- Inadeqaude competence at site
+- Problem at triage
+- 	Problem with management/ trauma criteria 
+- No neurosurgeon at site 
+- Problem with Tertriry survey after stabilisation/resuscitation  
+- Problem with management/logistics 
+- Wrong level of care 
+- Inadequate resources 
+- Problem with logistic and technique 
+- Exemplary treatment

The model was adjusted for gender, age and mortalit. All variables with exception for age were categorical. 



**Data soures/measurement**

The Swedish trauma registry SweTrau includes all trauma patients with a NISS >15 or who have triggered an alarm with trauma team activation in Sweden from 2010 to date. The trauma care quality database at KUH includes data from trauma patients treated at the hospital from 2014-2021. In the years 2014-2017, patients all random set of patients with an Injury severity score (ISS) of 9 or higher were included. From 2017, all patients included in the dataset have been reviewed at a M&M conference held at the the Karolinska University hospital. 

In this study, all patients within the Karolinska University hospital trauma quality registry reviewed at a M&M conference were included. For these patients, data from the Swedish trauma registry by SweTrau were collected to a merged dataset. The merged dataset was To prevent bias, the multivariable regression model was developed using a simulated scrambled dataset with random data. The algorithm for the model was developed step-by-step and then evaluated by a trained programmer and statistician before being applied on the real data. Variables such as ID-number and name were scrambled and anonymised throughout analysis of the real dataset as well.  then divided into four cohorts; (1) blunt multisystem trauma with traumatic brain injury, (2) blunt multisystem trauma without traumatic brain injury, (3) penetrating trauma, (4) isolated severe traumatic brain injury



**Bias** 

To prevent bias, the multivariable regression model will be developed using a simulated scrambled dataset with random data. The algorithm for the model will be developed step-by-step and then evaluated by a trained programmer and statistician before being applied on theTo prevent bias, the multivariable regression model was developed using a simulated scrambled dataset with random data. The algorithm for the model was developed step-by-step and then evaluated by a trained programmer and statistician before being applied on the real data. Variables such as ID-number and name were scrambled and anonymised throughout analysis of the real dataset as well.   real data. Variables such as ID-number and name will be scrambled and anonymised throughout analysis of the real dataset as well.  


**Study size** 








